name: build-caddy
permissions: read-all
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  schedule:
    # Run at 02:01 on the 3rd of every month 
    - cron: '1 2 3 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Set Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          
      - name: Get current time
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}
          
      - name: Build and Push images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REPO }}:latest
            ${{ env.REPO }}:${{ env.BUILD_DATE }}
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
